### ISSUE TITLE
vLLM examples aren't working

### ISSUE THREAD

**Issue by mattt** [nateraw/replicate-examples#3]
I've gotten a [report](https://github.com/replicate/cog/issues/1567) about Cog not working with some of the language models in this repo. In particular, [llama-2-70b-chat-awq](https://github.com/nateraw/replicate-examples/tree/main/llama-2-70b-chat-awq) and [mixtral-instruct](https://github.com/nateraw/replicate-examples/tree/main/mixtral-instruct).

Could you please consider removing these examples and/or linking instead to the new, official [Cog project for vLLM](https://github.com/replicate/cog-vllm)?

**Comment by nateraw** [comment]
Hey @mattt! :)

Ah yea, sorry. Lotta sketchiness in here. Down to rm/point to official project! if it's getting annoying for you, a PR would be much appreciated 🙏  - else I'll get to it when I find a chance :)
